export const sayings = [
  "what’s cooking today?",
  "hungry for something new?",
  "ready to spice things up?",
  "craving something delicious?",
  "looking for inspiration?",
  "find your perfect dish!",
  "what will you create today?",
  "taste the possibilities!",
  "explore flavors!",
  "feeling hungry?",
  "what’s your next flavor adventure?",
  "time to get cooking!",
  "discover something tasty!",
  "in the mood for something special?",
  "what’s on the menu today?",
  "your next dish awaits!",
  "unlock a world of flavor!",
  "time to whip up something great!",
  "what will you savor today?",
  "cooking made easy, what’s next?",
  "ignite your taste buds!",
  "dive into something flavorful!",
  "let's cook up some magic!",
  "what flavor will you try today?",
  "discover new tastes, one dish at a time!",
  "your culinary journey starts here!",
  "get ready for a flavor explosion!",
  "explore new recipes and delicious ideas!",
  "today’s flavor journey begins now!",
  "let your kitchen creativity run wild!",
  "get inspired to cook something fresh!",
  "satisfy your cravings with something new!",
  "where will your taste buds take you today?",
  "cook up something unforgettable!",
  "flavors from around the world, in your kitchen!",
  "experiment with new ingredients today!",
  "what’s the dish of the day?",
  "the perfect meal is just a recipe away!",
  "create your masterpiece in the kitchen!",
  "ready for a tasty twist?",
  "find your next favorite recipe!"
];
